{
  "total_count": 5,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/32644",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/32644",
      "id": 555422490,
      "node_id": "MDU6SXNzdWU1NTU0MjI0OTA=",
      "number": 32644,
      "title": "DISABLED test_quantized_rnn (test_quanization.PostTrainingDynamicQuantTest)",
      "user": {
        "login": "rohan-varma",
        "id": 8039770,
        "node_id": "MDQ6VXNlcjgwMzk3NzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rohan-varma",
        "html_url": "https://github.com/rohan-varma",
        "followers_url": "https://api.github.com/users/rohan-varma/followers",
        "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
        "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
        "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
        "repos_url": "https://api.github.com/users/rohan-varma/repos",
        "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/quantization",
          "name": "quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "jianyuh",
        "id": 2187690,
        "node_id": "MDQ6VXNlcjIxODc2OTA=",
        "avatar_url": "https://avatars3.githubusercontent.com/u/2187690?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/jianyuh",
        "html_url": "https://github.com/jianyuh",
        "followers_url": "https://api.github.com/users/jianyuh/followers",
        "following_url": "https://api.github.com/users/jianyuh/following{/other_user}",
        "gists_url": "https://api.github.com/users/jianyuh/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/jianyuh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jianyuh/subscriptions",
        "organizations_url": "https://api.github.com/users/jianyuh/orgs",
        "repos_url": "https://api.github.com/users/jianyuh/repos",
        "events_url": "https://api.github.com/users/jianyuh/events{/privacy}",
        "received_events_url": "https://api.github.com/users/jianyuh/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "jianyuh",
          "id": 2187690,
          "node_id": "MDQ6VXNlcjIxODc2OTA=",
          "avatar_url": "https://avatars3.githubusercontent.com/u/2187690?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/jianyuh",
          "html_url": "https://github.com/jianyuh",
          "followers_url": "https://api.github.com/users/jianyuh/followers",
          "following_url": "https://api.github.com/users/jianyuh/following{/other_user}",
          "gists_url": "https://api.github.com/users/jianyuh/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/jianyuh/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/jianyuh/subscriptions",
          "organizations_url": "https://api.github.com/users/jianyuh/orgs",
          "repos_url": "https://api.github.com/users/jianyuh/repos",
          "events_url": "https://api.github.com/users/jianyuh/events{/privacy}",
          "received_events_url": "https://api.github.com/users/jianyuh/received_events",
          "type": "User",
          "site_admin": false
        },
        {
          "login": "z-a-f",
          "id": 4216323,
          "node_id": "MDQ6VXNlcjQyMTYzMjM=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/z-a-f",
          "html_url": "https://github.com/z-a-f",
          "followers_url": "https://api.github.com/users/z-a-f/followers",
          "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
          "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
          "organizations_url": "https://api.github.com/users/z-a-f/orgs",
          "repos_url": "https://api.github.com/users/z-a-f/repos",
          "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
          "received_events_url": "https://api.github.com/users/z-a-f/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 15,
      "created_at": "2020-01-27T08:22:49Z",
      "updated_at": "2020-03-03T19:34:48Z",
      "closed_at": null,
      "author_association": "MEMBER",
      "body": "## 🐛 Bug\r\n\r\ntes_quantized_rnn is flaky, see https://app.circleci.com/jobs/github/pytorch/pytorch/4343194\r\nSee example failure: \r\n```\r\nJan 26 08:10:23 ======================================================================\r\nJan 26 08:10:23 ERROR [0.186s]: test_quantized_rnn (__main__.PostTrainingDynamicQuantTest)\r\nJan 26 08:10:23 ----------------------------------------------------------------------\r\nJan 26 08:10:23 Traceback (most recent call last):\r\nJan 26 08:10:23   File \"test_quantization.py\", line 722, in test_quantized_rnn\r\nJan 26 08:10:23     y, (h, c) = cell_dq(x, (h, c))\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 540, in __call__\r\nJan 26 08:10:23     result = self.forward(*input, **kwargs)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 373, in forward\r\nJan 26 08:10:23     return self.forward_tensor(input, hx)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 334, in forward_tensor\r\nJan 26 08:10:23     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 315, in forward_impl\r\nJan 26 08:10:23     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nJan 26 08:10:23 RuntimeError: quantization scale should be > 0\r\n```\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34260",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34260/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34260/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34260/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34260",
      "id": 575758658,
      "node_id": "MDU6SXNzdWU1NzU3NTg2NTg=",
      "number": 34260,
      "title": "DISABLED test_torchscript_functions_not_supported (__main__.JitRpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/jit",
          "name": "jit",
          "color": "c5def5",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "xush6528",
        "id": 7608630,
        "node_id": "MDQ6VXNlcjc2MDg2MzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/7608630?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/xush6528",
        "html_url": "https://github.com/xush6528",
        "followers_url": "https://api.github.com/users/xush6528/followers",
        "following_url": "https://api.github.com/users/xush6528/following{/other_user}",
        "gists_url": "https://api.github.com/users/xush6528/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/xush6528/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xush6528/subscriptions",
        "organizations_url": "https://api.github.com/users/xush6528/orgs",
        "repos_url": "https://api.github.com/users/xush6528/repos",
        "events_url": "https://api.github.com/users/xush6528/events{/privacy}",
        "received_events_url": "https://api.github.com/users/xush6528/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "xush6528",
          "id": 7608630,
          "node_id": "MDQ6VXNlcjc2MDg2MzA=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/7608630?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/xush6528",
          "html_url": "https://github.com/xush6528",
          "followers_url": "https://api.github.com/users/xush6528/followers",
          "following_url": "https://api.github.com/users/xush6528/following{/other_user}",
          "gists_url": "https://api.github.com/users/xush6528/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/xush6528/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/xush6528/subscriptions",
          "organizations_url": "https://api.github.com/users/xush6528/orgs",
          "repos_url": "https://api.github.com/users/xush6528/repos",
          "events_url": "https://api.github.com/users/xush6528/events{/privacy}",
          "received_events_url": "https://api.github.com/users/xush6528/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-04T20:48:06Z",
      "updated_at": "2020-03-04T21:01:12Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "test_torchscript_functions_not_supported is flaky\r\n\r\nPassed :\r\nhttps://app.circleci.com/jobs/github/pytorch/pytorch/4691744\r\n\r\nFailed:\r\nhttps://app.circleci.com/jobs/github/pytorch/pytorch/4692485\r\n\r\n```\r\nMar 04 20:33:44 Running tests...\r\nMar 04 20:33:44 ----------------------------------------------------------------------\r\nMar 04 20:33:48 ...[E request_callback.cpp:39] Received error while processing request type 0: attempted to get undefined function python_function (get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:69)\r\nMar 04 20:33:48 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f31d8c6679a in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:48 frame #1: <unknown function> + 0x65b5bd (0x7f31d98625bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #2: torch::distributed::rpc::RequestCallbackImpl::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType, long) const + 0x18dc (0x7f31d9aa823c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #3: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0x55 (0x7f31d9aa94a5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #4: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x33 (0x7f31d6579ed3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nMar 04 20:33:48 frame #5: <unknown function> + 0x88326b (0x7f31d9a8a26b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x2fb (0x7f31d8c57cab in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:48 frame #7: <unknown function> + 0xc8421 (0x7f31d915b421 in /opt/conda/lib/libstdc++.so.6)\r\nMar 04 20:33:48 frame #8: <unknown function> + 0x76ba (0x7f31e1d666ba in /lib/x86_64-linux-gnu/libpthread.so.0)\r\nMar 04 20:33:48 frame #9: clone + 0x6d (0x7f31e1a9c41d in /lib/x86_64-linux-gnu/libc.so.6)\r\nMar 04 20:33:48 \r\nMar 04 20:33:49 .[E request_callback.cpp:39] Received error while processing request type 0: attempted to get undefined function nonexisting_script (get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:69)\r\nMar 04 20:33:49 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f800502a79a in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:49 frame #1: <unknown function> + 0x65b5bd (0x7f8005c265bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #2: torch::distributed::rpc::RequestCallbackImpl::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType, long) const + 0x18dc (0x7f8005e6c23c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #3: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0x55 (0x7f8005e6d4a5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #4: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x33 (0x7f800293ded3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nMar 04 20:33:49 frame #5: <unknown function> + 0x88326b (0x7f8005e4e26b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x2fb (0x7f800501bcab in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:49 frame #7: <unknown function> + 0xc8421 (0x7f800551f421 in /opt/conda/lib/libstdc++.so.6)\r\nMar 04 20:33:49 frame #8: <unknown function> + 0x76ba (0x7f800e12a6ba in /lib/x86_64-linux-gnu/libpthread.so.0)\r\nMar 04 20:33:49 frame #9: clone + 0x6d (0x7f800de6041d in /lib/x86_64-linux-gnu/libc.so.6)\r\nMar 04 20:33:49 \r\nMar 04 20:33:50 .[E request_callback.cpp:39] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.\r\nMar 04 20:33:50 Traceback of TorchScript (most recent call last):\r\nMar 04 20:33:50   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 140, in raise_script\r\nMar 04 20:33:50 @torch.jit.script\r\nMar 04 20:33:50 def raise_script():\r\nMar 04 20:33:50     raise RuntimeError(\"Expected error\")\r\nMar 04 20:33:50     ~~~~~~~~~~~~~~~~~~~~ <--- HERE\r\nMar 04 20:33:50     return 0\r\nMar 04 20:33:50 RuntimeError: Exception\r\nMar 04 20:33:50 \r\nMar 04 20:35:07 ...............Process process 3:\r\nMar 04 20:35:07 Traceback (most recent call last):\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\r\nMar 04 20:35:07     self.run()\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 93, in run\r\nMar 04 20:35:07     self._target(*self._args, **self._kwargs)\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 243, in _run\r\nMar 04 20:35:07     getattr(self, test_name)()\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 68, in new_test_method\r\nMar 04 20:35:07     return_value = old_test_method(self, *arg, **kwargs)\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 496, in test_torchscript_functions_not_supported\r\nMar 04 20:35:07     ret = rpc.rpc_sync(\"worker{}\".format(dst_rank), MyScriptClass, args=())\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:07     return func(*args, **kwargs)\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 526, in rpc_sync\r\nMar 04 20:35:07     return fut.wait()\r\nMar 04 20:35:07 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.\r\nMar 04 20:35:08 Process process 1:\r\nMar 04 20:35:08 Traceback (most recent call last):\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\r\nMar 04 20:35:08     self.run()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 93, in run\r\nMar 04 20:35:08     self._target(*self._args, **self._kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 243, in _run\r\nMar 04 20:35:08     getattr(self, test_name)()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 71, in new_test_method\r\nMar 04 20:35:08     rpc.shutdown(graceful=clean_shutdown)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 237, in shutdown\r\nMar 04 20:35:08     _wait_all_workers()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 164, in _wait_all_workers\r\nMar 04 20:35:08     args=(sequence_id, self_worker_name,),\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 526, in rpc_sync\r\nMar 04 20:35:08     return fut.wait()\r\nMar 04 20:35:08 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.\r\nMar 04 20:35:08 Process process 2:\r\nMar 04 20:35:08 Traceback (most recent call last):\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\r\nMar 04 20:35:08     self.run()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 93, in run\r\nMar 04 20:35:08     self._target(*self._args, **self._kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 243, in _run\r\nMar 04 20:35:08     getattr(self, test_name)()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 71, in new_test_method\r\nMar 04 20:35:08     rpc.shutdown(graceful=clean_shutdown)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 237, in shutdown\r\nMar 04 20:35:08     _wait_all_workers()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 164, in _wait_all_workers\r\nMar 04 20:35:08     args=(sequence_id, self_worker_name,),\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 526, in rpc_sync\r\nMar 04 20:35:08     return fut.wait()\r\nMar 04 20:35:08 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.\r\nMar 04 20:35:48 E.\r\nMar 04 20:35:48 ======================================================================\r\nMar 04 20:35:48 ERROR [100.047s]: test_torchscript_functions_not_supported (__main__.JitRpcTestWithSpawn)\r\nMar 04 20:35:48 ----------------------------------------------------------------------\r\nMar 04 20:35:48 Traceback (most recent call last):\r\nMar 04 20:35:48   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nMar 04 20:35:48     self._join_processes(fn)\r\nMar 04 20:35:48   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in _join_processes\r\nMar 04 20:35:48     self._check_return_codes(elapsed_time)\r\nMar 04 20:35:48   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 275, in _check_return_codes\r\nMar 04 20:35:48     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nMar 04 20:35:48 RuntimeError: Process 0 terminated or timed out after 100.02777481079102 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34237",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34237/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34237/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34237/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34237",
      "id": 575659841,
      "node_id": "MDU6SXNzdWU1NzU2NTk4NDE=",
      "number": 34237,
      "title": "DISABLED test_stress_heavy_rpc_torchscript (__main__.RpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/jit",
          "name": "jit",
          "color": "c5def5",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "zhaojuanmao",
        "id": 48731194,
        "node_id": "MDQ6VXNlcjQ4NzMxMTk0",
        "avatar_url": "https://avatars0.githubusercontent.com/u/48731194?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/zhaojuanmao",
        "html_url": "https://github.com/zhaojuanmao",
        "followers_url": "https://api.github.com/users/zhaojuanmao/followers",
        "following_url": "https://api.github.com/users/zhaojuanmao/following{/other_user}",
        "gists_url": "https://api.github.com/users/zhaojuanmao/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/zhaojuanmao/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zhaojuanmao/subscriptions",
        "organizations_url": "https://api.github.com/users/zhaojuanmao/orgs",
        "repos_url": "https://api.github.com/users/zhaojuanmao/repos",
        "events_url": "https://api.github.com/users/zhaojuanmao/events{/privacy}",
        "received_events_url": "https://api.github.com/users/zhaojuanmao/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "zhaojuanmao",
          "id": 48731194,
          "node_id": "MDQ6VXNlcjQ4NzMxMTk0",
          "avatar_url": "https://avatars0.githubusercontent.com/u/48731194?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/zhaojuanmao",
          "html_url": "https://github.com/zhaojuanmao",
          "followers_url": "https://api.github.com/users/zhaojuanmao/followers",
          "following_url": "https://api.github.com/users/zhaojuanmao/following{/other_user}",
          "gists_url": "https://api.github.com/users/zhaojuanmao/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/zhaojuanmao/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/zhaojuanmao/subscriptions",
          "organizations_url": "https://api.github.com/users/zhaojuanmao/orgs",
          "repos_url": "https://api.github.com/users/zhaojuanmao/repos",
          "events_url": "https://api.github.com/users/zhaojuanmao/events{/privacy}",
          "received_events_url": "https://api.github.com/users/zhaojuanmao/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-03-04T18:39:54Z",
      "updated_at": "2020-03-04T19:53:44Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "`test_stress_heavy_rpc_torchscript` is flaky\r\n\r\nhttps://app.circleci.com/jobs/github/pytorch/pytorch/4688332\r\n\r\n```\r\nMar 04 09:25:35 ======================================================================\r\nMar 04 09:25:35 ERROR [361.213s]: test_stress_heavy_rpc_torchscript (__main__.RpcTestWithSpawn)\r\nMar 04 09:25:35 ----------------------------------------------------------------------\r\nMar 04 09:25:35 Traceback (most recent call last):\r\nMar 04 09:25:35   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nMar 04 09:25:35     self._join_processes(fn)\r\nMar 04 09:25:35   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in _join_processes\r\nMar 04 09:25:35     self._check_return_codes(elapsed_time)\r\nMar 04 09:25:35   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 275, in _check_return_codes\r\nMar 04 09:25:35     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nMar 04 09:25:35 RuntimeError: Process 1 terminated or timed out after 361.193176984787 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34213",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34213",
      "id": 575502768,
      "node_id": "MDU6SXNzdWU1NzU1MDI3Njg=",
      "number": 34213,
      "title": "DISABLED test_script_pack_padded_sequence (test_jit.TestScript)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/jit",
          "name": "jit",
          "color": "c5def5",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-04T15:29:15Z",
      "updated_at": "2020-03-04T15:50:48Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Previous failed runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682966\r\n\r\nSubsequent succeeded runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682247\r\nhttps://circleci.com/gh/pytorch/pytorch/4682241\r\n\r\nToday, it consistently fails:\r\nhttps://circleci.com/gh/pytorch/pytorch/4687625\r\nhttps://circleci.com/gh/pytorch/pytorch/4687610\r\nhttps://circleci.com/gh/pytorch/pytorch/4686149\r\n\r\n@ljk53 tried reverting the seemingly culprit PR #32814 and #34055, but the error persist. \r\n\r\nI am going to disable this test while JIT team investigating it. \n\ncc @ezyang @gchanan @zou3519 @suo",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/31750",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/31750",
      "id": 544251558,
      "node_id": "MDU6SXNzdWU1NDQyNTE1NTg=",
      "number": 31750,
      "title": "DISABLED test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset10::test_interpolate_downsample",
      "user": {
        "login": "Krovatkin",
        "id": 5086322,
        "node_id": "MDQ6VXNlcjUwODYzMjI=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5086322?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Krovatkin",
        "html_url": "https://github.com/Krovatkin",
        "followers_url": "https://api.github.com/users/Krovatkin/followers",
        "following_url": "https://api.github.com/users/Krovatkin/following{/other_user}",
        "gists_url": "https://api.github.com/users/Krovatkin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Krovatkin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Krovatkin/subscriptions",
        "organizations_url": "https://api.github.com/users/Krovatkin/orgs",
        "repos_url": "https://api.github.com/users/Krovatkin/repos",
        "events_url": "https://api.github.com/users/Krovatkin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Krovatkin/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1679533716,
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped",
          "name": "skipped",
          "color": "bfdadc",
          "default": false,
          "description": "Denotes a (flaky) test currently skipped in CI."
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2019-12-31T19:03:16Z",
      "updated_at": "2020-01-02T14:49:19Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Temporarily disabling a flakey test.",
      "score": 0.0
    }
  ]
}
