{
  "total_count": 13,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/47128",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/47128/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/47128/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/47128/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/47128",
      "id": 733427450,
      "node_id": "MDU6SXNzdWU3MzM0Mjc0NTA=",
      "number": 47128,
      "title": "AMP doesn't gracefully handle optimizers for disabled regions",
      "user": {
        "login": "danieltudosiu",
        "id": 10502740,
        "node_id": "MDQ6VXNlcjEwNTAyNzQw",
        "avatar_url": "https://avatars2.githubusercontent.com/u/10502740?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/danieltudosiu",
        "html_url": "https://github.com/danieltudosiu",
        "followers_url": "https://api.github.com/users/danieltudosiu/followers",
        "following_url": "https://api.github.com/users/danieltudosiu/following{/other_user}",
        "gists_url": "https://api.github.com/users/danieltudosiu/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/danieltudosiu/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/danieltudosiu/subscriptions",
        "organizations_url": "https://api.github.com/users/danieltudosiu/orgs",
        "repos_url": "https://api.github.com/users/danieltudosiu/repos",
        "events_url": "https://api.github.com/users/danieltudosiu/events{/privacy}",
        "received_events_url": "https://api.github.com/users/danieltudosiu/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1972560798,
          "node_id": "MDU6TGFiZWwxOTcyNTYwNzk4",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20amp%20(automated%20mixed%20precision)",
          "name": "module: amp (automated mixed precision)",
          "color": "f7e101",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-10-30T18:38:28Z",
      "updated_at": "2020-10-30T19:31:07Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "## üêõ Bug\r\n\r\nWhen we have optimizers for multiple parts of the networks and one such part has the amp context disabled through     `@torch.cuda.amp.autocast(enabled=False)` the optimizer for that part will error out with `AssertionError: No inf checks were recorded for this optimizer.`\r\n\r\n## To Reproduce\r\n\r\nCreate a VAE and have the code processor (where we split into mean and logvar, do the reparameterization trick, generate the z) set to `@torch.cuda.amp.autocast(enabled=False)` and dedicate an optimizer to it. If you follow the multi optimizer example the code will error out.\r\n\r\n## Expected behavior\r\n\r\nAllow the scaler to check if amp is active for those variables and if not, to not error out in regards to the inf checks.\r\n\r\n## Environment\r\n - PyTorch Version (e.g., 1.0): 1.6\r\n - OS (e.g., Linux): Ubuntu 18.04\r\n - How you installed PyTorch (`conda`, `pip`, source): pip\r\n - Build command you used (if compiling from source): N/A\r\n - Python version: 3.6\r\n - CUDA/cuDNN version: 11/7.6\r\n - GPU models and configuration: Titan V\r\n\n\ncc @mcarilli",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/38491",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/38491",
      "id": 618421559,
      "node_id": "MDU6SXNzdWU2MTg0MjE1NTk=",
      "number": 38491,
      "title": "DISABLED ParallelWorkersTest.testParallelWorkersShutdownFun ",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-05-14T17:45:34Z",
      "updated_at": "2020-09-03T23:40:50Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/169923/workflows/d66ca278-d55c-462b-96cb-55623ce713f7/jobs/5472514/steps\r\n\r\n```\r\nMay 14 07:37:27 =================================== FAILURES ===================================\r\nMay 14 07:37:27 ______________ ParallelWorkersTest.testParallelWorkersShutdownFun ______________\r\nMay 14 07:37:27 \r\nMay 14 07:37:27 self = <caffe2.python.parallel_workers_test.ParallelWorkersTest testMethod=testParallelWorkersShutdownFun>\r\nMay 14 07:37:27 \r\nMay 14 07:37:27     def testParallelWorkersShutdownFun(self):\r\nMay 14 07:37:27         workspace.ResetWorkspace()\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         queue = create_queue()\r\nMay 14 07:37:27         dummy_worker = create_worker(queue, lambda worker_id: str(worker_id))\r\nMay 14 07:37:27         workspace.FeedBlob('data', 'not shutdown')\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         def shutdown_fun():\r\nMay 14 07:37:27             workspace.FeedBlob('data', 'shutdown')\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         worker_coordinator = parallel_workers.init_workers(\r\nMay 14 07:37:27             dummy_worker, shutdown_fun=shutdown_fun\r\nMay 14 07:37:27         )\r\nMay 14 07:37:27         worker_coordinator.start()\r\nMay 14 07:37:27     \r\nMay 14 07:37:27 >       self.assertTrue(worker_coordinator.stop())\r\nMay 14 07:37:27 E       AssertionError: False is not true\r\nMay 14 07:37:27 \r\nMay 14 07:37:27 ../.local/lib/python3.6/site-packages/caffe2/python/parallel_workers_test.py:116: AssertionError\r\nMay 14 07:37:27 ----------------------------- Captured stdout call -----------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/45846",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/45846/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/45846/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/45846/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/45846",
      "id": 714965813,
      "node_id": "MDU6SXNzdWU3MTQ5NjU4MTM=",
      "number": 45846,
      "title": "DISABLED test_backward_python_udf_error (__main__.TensorPipeDistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed",
          "name": "oncall: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Add this issue/PR to distributed oncall triage queue"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-10-05T15:58:57Z",
      "updated_at": "2020-10-06T07:04:12Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "```\r\nOct 03 06:32:41 ======================================================================\r\nOct 03 06:32:41 ERROR [1.738s]: test_backward_python_udf_error (__main__.TensorPipeDistAutogradTestWithSpawn)\r\nOct 03 06:32:41 ----------------------------------------------------------------------\r\nOct 03 06:32:41 Traceback (most recent call last):\r\nOct 03 06:32:41   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in wrapper\r\nOct 03 06:32:41     self._join_processes(fn)\r\nOct 03 06:32:41   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 373, in _join_processes\r\nOct 03 06:32:41     self._check_return_codes(elapsed_time)\r\nOct 03 06:32:41   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 409, in _check_return_codes\r\nOct 03 06:32:41     raise RuntimeError(error)\r\nOct 03 06:32:41 RuntimeError: Processes 0 exited with error code 10\r\nOct 03 06:32:41 \r\nOct 03 06:32:41 ----------------------------------------------------------------------\r\n```\r\n\r\n```\r\nOct 03 06:21:23   test_backward_python_udf_error (__main__.TensorPipeDistAutogradTestWithSpawn) ... /opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)\r\nOct 03 06:21:23   return torch._C._cuda_getDeviceCount() > 0\r\nOct 03 06:21:23 ERROR:root:Caught exception: \r\nOct 03 06:21:23 RuntimeError: Error on Node 2: Error on Node 3: could not compute gradients for some functions\r\nOct 03 06:21:23 \r\nOct 03 06:21:23 During handling of the above exception, another exception occurred:\r\nOct 03 06:21:23 \r\nOct 03 06:21:23 Traceback (most recent call last):\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 259, in wrapper\r\nOct 03 06:21:23     fn()\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 90, in new_test_method\r\nOct 03 06:21:23     return_value = old_test_method(self, *arg, **kwargs)\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py\", line 1420, in test_backward_python_udf_error\r\nOct 03 06:21:23     dist_autograd.backward(context_id, [loss.sum()])\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/unittest/case.py\", line 217, in __exit__\r\nOct 03 06:21:23     expected_regex.pattern, str(exc_value)))\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/unittest/case.py\", line 135, in _raiseFailure\r\nOct 03 06:21:23     raise self.test_case.failureException(msg)\r\nOct 03 06:21:23 AssertionError: \"Simulate error on backward pass\" does not match \"Error on Node 2: Error on Node 3: could not compute gradients for some functions\"\r\nOct 03 06:21:23 exiting process with exit code: 10\r\nOct 03 06:21:23 /opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /var/lib/jenkins/workspace/c10/cuda/CUDAFunctions.cpp:100.)\r\nOct 03 06:21:23   return torch._C._cuda_getDeviceCount() > 0\r\nOct 03 06:21:23 ERROR:root:Caught exception: \r\nOct 03 06:21:23 RuntimeError: Error on Node 0: Error on Node 1: Error on Node 2: 'NoneType' object is not callable\r\nOct 03 06:21:23 \r\nOct 03 06:21:23 During handling of the above exception, another exception occurred:\r\nOct 03 06:21:23 \r\nOct 03 06:21:23 Traceback (most recent call last):\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 259, in wrapper\r\nOct 03 06:21:23     fn()\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 90, in new_test_method\r\nOct 03 06:21:23     return_value = old_test_method(self, *arg, **kwargs)\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/dist_autograd_test.py\", line 1420, in test_backward_python_udf_error\r\nOct 03 06:21:23     dist_autograd.backward(context_id, [loss.sum()])\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/unittest/case.py\", line 217, in __exit__\r\nOct 03 06:21:23     expected_regex.pattern, str(exc_value)))\r\nOct 03 06:21:23   File \"/opt/conda/lib/python3.6/unittest/case.py\", line 135, in _raiseFailure\r\nOct 03 06:21:23     raise self.test_case.failureException(msg)\r\nOct 03 06:21:23 AssertionError: \"Simulate error on backward pass\" does not match \"Error on Node 0: Error on Node 1: Error on Node 2: 'NoneType' object is not callable\"\r\nOct 03 06:21:23 exiting process with exit code: 10\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby @agolynski",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40303",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40303/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40303/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40303/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40303",
      "id": 642201370,
      "node_id": "MDU6SXNzdWU2NDIyMDEzNzA=",
      "number": 40303,
      "title": "DISABLED test_local_shutdown (__main__.TensorPipeAgentRpcTestWithSpawn)",
      "user": {
        "login": "lw",
        "id": 120810,
        "node_id": "MDQ6VXNlcjEyMDgxMA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/120810?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lw",
        "html_url": "https://github.com/lw",
        "followers_url": "https://api.github.com/users/lw/followers",
        "following_url": "https://api.github.com/users/lw/following{/other_user}",
        "gists_url": "https://api.github.com/users/lw/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lw/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lw/subscriptions",
        "organizations_url": "https://api.github.com/users/lw/orgs",
        "repos_url": "https://api.github.com/users/lw/repos",
        "events_url": "https://api.github.com/users/lw/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lw/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "lw",
        "id": 120810,
        "node_id": "MDQ6VXNlcjEyMDgxMA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/120810?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lw",
        "html_url": "https://github.com/lw",
        "followers_url": "https://api.github.com/users/lw/followers",
        "following_url": "https://api.github.com/users/lw/following{/other_user}",
        "gists_url": "https://api.github.com/users/lw/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lw/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lw/subscriptions",
        "organizations_url": "https://api.github.com/users/lw/orgs",
        "repos_url": "https://api.github.com/users/lw/repos",
        "events_url": "https://api.github.com/users/lw/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lw/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "lw",
          "id": 120810,
          "node_id": "MDQ6VXNlcjEyMDgxMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/120810?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/lw",
          "html_url": "https://github.com/lw",
          "followers_url": "https://api.github.com/users/lw/followers",
          "following_url": "https://api.github.com/users/lw/following{/other_user}",
          "gists_url": "https://api.github.com/users/lw/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/lw/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/lw/subscriptions",
          "organizations_url": "https://api.github.com/users/lw/orgs",
          "repos_url": "https://api.github.com/users/lw/repos",
          "events_url": "https://api.github.com/users/lw/events{/privacy}",
          "received_events_url": "https://api.github.com/users/lw/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-06-19T20:24:20Z",
      "updated_at": "2020-09-28T07:49:01Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/183267/workflows/af7c3c56-4437-47f7-ad4c-f816e4485705/jobs/5930451/steps\r\n\r\n```\r\nJun 19 20:19:53 ======================================================================\r\nJun 19 20:19:53 ERROR [100.089s]: test_local_shutdown (__main__.TensorPipeAgentRpcTestWithSpawn)\r\nJun 19 20:19:53 ----------------------------------------------------------------------\r\nJun 19 20:19:53 Traceback (most recent call last):\r\nJun 19 20:19:53   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 19 20:19:53     self._join_processes(fn)\r\nJun 19 20:19:53   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 19 20:19:53     self._check_return_codes(elapsed_time)\r\nJun 19 20:19:53   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 344, in _check_return_codes\r\nJun 19 20:19:53     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nJun 19 20:19:53 RuntimeError: Process 0 terminated or timed out after 100.07188177108765 seconds\r\nJun 19 20:19:53 \r\nJun 19 20:19:53 ----------------------------------------------------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/44734",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/44734/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/44734/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/44734/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/44734",
      "id": 702235684,
      "node_id": "MDU6SXNzdWU3MDIyMzU2ODQ=",
      "number": 44734,
      "title": "DISABLED test_future_passed_between_python_and_jit (__main__.ProcessGroupJitRpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20jit",
          "name": "oncall: jit",
          "color": "c5def5",
          "default": false,
          "description": "Add this issue/PR to JIT oncall triage queue"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "wanchaol",
        "id": 9443650,
        "node_id": "MDQ6VXNlcjk0NDM2NTA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/9443650?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/wanchaol",
        "html_url": "https://github.com/wanchaol",
        "followers_url": "https://api.github.com/users/wanchaol/followers",
        "following_url": "https://api.github.com/users/wanchaol/following{/other_user}",
        "gists_url": "https://api.github.com/users/wanchaol/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/wanchaol/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wanchaol/subscriptions",
        "organizations_url": "https://api.github.com/users/wanchaol/orgs",
        "repos_url": "https://api.github.com/users/wanchaol/repos",
        "events_url": "https://api.github.com/users/wanchaol/events{/privacy}",
        "received_events_url": "https://api.github.com/users/wanchaol/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "wanchaol",
          "id": 9443650,
          "node_id": "MDQ6VXNlcjk0NDM2NTA=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/9443650?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/wanchaol",
          "html_url": "https://github.com/wanchaol",
          "followers_url": "https://api.github.com/users/wanchaol/followers",
          "following_url": "https://api.github.com/users/wanchaol/following{/other_user}",
          "gists_url": "https://api.github.com/users/wanchaol/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/wanchaol/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/wanchaol/subscriptions",
          "organizations_url": "https://api.github.com/users/wanchaol/orgs",
          "repos_url": "https://api.github.com/users/wanchaol/repos",
          "events_url": "https://api.github.com/users/wanchaol/events{/privacy}",
          "received_events_url": "https://api.github.com/users/wanchaol/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-09-15T20:27:26Z",
      "updated_at": "2020-09-21T22:04:01Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/214167/workflows/f701b331-f6de-4bd9-b5df-ab014f654485/jobs/7480330/steps\r\n\r\n```\r\nSep 15 09:32:47 ======================================================================\r\nSep 15 09:32:47 ERROR [0.930s]: test_future_passed_between_python_and_jit (__main__.ProcessGroupJitRpcTestWithSpawn)\r\nSep 15 09:32:47 ----------------------------------------------------------------------\r\nSep 15 09:32:47 Traceback (most recent call last):\r\nSep 15 09:32:47   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 244, in wrapper\r\nSep 15 09:32:47     self._join_processes(fn)\r\nSep 15 09:32:47   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 361, in _join_processes\r\nSep 15 09:32:47     self._check_return_codes(elapsed_time)\r\nSep 15 09:32:47   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 397, in _check_return_codes\r\nSep 15 09:32:47     raise RuntimeError(error)\r\nSep 15 09:32:47 RuntimeError: Processes 3 exited with error code 10\r\n```\r\n\r\n```\r\nSep 15 09:28:59   test_future_passed_between_python_and_jit (__main__.ProcessGroupJitRpcTestWithSpawn) ... [E request_callback_no_python.cpp:618] Received error while processing request type 0: attempted to get undefined function two_args_two_kwargs\r\nSep 15 09:28:59 Exception raised from get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:71 (most recent call first):\r\nSep 15 09:28:59 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f874517768b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nSep 15 09:28:59 frame #1: <unknown function> + 0x7ac264 (0x7f875b5ff264 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nSep 15 09:28:59 frame #2: torch::distributed::rpc::RequestCallbackImpl::processScriptCall(torch::distributed::rpc::ScriptCall&, std::function<void (torch::distributed::rpc::Message)> const&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, long, std::shared_ptr<torch::utils::Future<torch::distributed::rpc::Message> > const&) const + 0xaf (0x7f875bbcf74f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nSep 15 09:28:59 frame #3: torch::distributed::rpc::RequestCallbackNoPython::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, long, std::shared_ptr<torch::utils::Future<torch::distributed::rpc::Message> > const&) const + 0x3f4 (0x7f87547bc304 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nSep 15 09:28:59 frame #4: torch::distributed::rpc::RequestCallbackImpl::processRpcWithErrors(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType const&, long, std::shared_ptr<torch::utils::Future<torch::distributed::rpc::Message> > const&) const + 0x2f (0x7f875bbd116f in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nSep 15 09:28:59 frame #5: <unknown function> + 0x353fa04 (0x7f87547b9a04 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nSep 15 09:28:59 frame #6: torch::distributed::rpc::RequestCallbackNoPython::processMessage(torch::distributed::rpc::Message&) const + 0x38b (0x7f87547bb2eb in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nSep 15 09:28:59 frame #7: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x1e (0x7f87547b813e in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nSep 15 09:28:59 frame #8: torch::distributed::rpc::ProcessGroupAgent::handleRecv(torch::distributed::rpc::RecvWork&) + 0xc4 (0x7f875bbaf284 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nSep 15 09:28:59 frame #9: <unknown function> + 0xd5d1b2 (0x7f875bbb01b2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nSep 15 09:28:59 frame #10: c10::ThreadPool::main_loop(unsigned long) + 0x2b3 (0x7f8745165e33 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nSep 15 09:28:59 frame #11: <unknown function> + 0xd0b10 (0x7f8767917b10 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)\r\nSep 15 09:28:59 frame #12: <unknown function> + 0x76ba (0x7f87851e76ba in /lib/x86_64-linux-gnu/libpthread.so.0)\r\nSep 15 09:28:59 frame #13: clone + 0x6d (0x7f8784f1d4dd in /lib/x86_64-linux-gnu/libc.so.6)\r\nSep 15 09:28:59 \r\nSep 15 09:28:59 ERROR:root:Caught exception: \r\nSep 15 09:28:59 Traceback (most recent call last):\r\nSep 15 09:28:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 247, in wrapper\r\nSep 15 09:28:59     fn()\r\nSep 15 09:28:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 71, in new_test_method\r\nSep 15 09:28:59     return_value = old_test_method(self, *arg, **kwargs)\r\nSep 15 09:28:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 278, in test_future_passed_between_python_and_jit\r\nSep 15 09:28:59     self.assertEqual(future_wait_in_script(ret_fut), expected_res)\r\nSep 15 09:28:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 121, in prof_func_call\r\nSep 15 09:28:59     return prof_callable(func_call, *args, **kwargs)\r\nSep 15 09:28:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 118, in prof_callable\r\nSep 15 09:28:59     return callable(*args, **kwargs)\r\nSep 15 09:28:59 RuntimeError: The following operation failed in the TorchScript interpreter.\r\nSep 15 09:28:59 Traceback of TorchScript (most recent call last):\r\nSep 15 09:28:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 276, in future_wait_in_script\r\nSep 15 09:28:59         @torch.jit.script\r\nSep 15 09:28:59         def future_wait_in_script(fut: Future[Tensor]) -> Tensor:\r\nSep 15 09:28:59             return fut.wait()\r\nSep 15 09:28:59                    ~~~~~~~~ <--- HERE\r\n```\n\ncc @ezyang @gchanan @zou3519 @gmagogsfm @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/39855",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/39855/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/39855/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/39855/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/39855",
      "id": 637037443,
      "node_id": "MDU6SXNzdWU2MzcwMzc0NDM=",
      "number": 39855,
      "title": "DISABLED test_backward_node_failure (__main__.TensorPipeDistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1076922545,
          "node_id": "MDU6TGFiZWwxMDc2OTIyNTQ1",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20autograd",
          "name": "module: autograd",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.autograd, and the autograd engine in general"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 7,
      "created_at": "2020-06-11T13:55:45Z",
      "updated_at": "2020-08-06T15:00:32Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/179019/workflows/89ef9bec-c13c-4d81-a817-5de5fed67cdf/jobs/5772385/steps https://app.circleci.com/pipelines/github/pytorch/pytorch/179483/workflows/b1faffb1-687b-4000-bae1-37fa2c93d7f5/jobs/5787474/steps\r\n\r\n```\r\nJun 10 18:19:54   test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:315] RPC agent for worker3 encountered error when reading incoming request: pipe closed\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:315] RPC agent for worker1 encountered error when reading incoming request: pipe closed\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 0: pipe closed\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 2: pipe closed\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:315] RPC agent for worker0 encountered error when reading incoming request: EOF: end of file\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:283] RPC agent for worker0 encountered error when writing outgoing response: EOF: end of file\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:315] RPC agent for worker2 encountered error when reading incoming request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 3: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 1: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:283] RPC agent for worker2 encountered error when writing outgoing response: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:21:33 Timing out after 100 seconds and killing subprocesses.\r\nJun 10 18:21:33 ERROR (100.075s)\r\n```\r\n\r\n```\r\nJun 10 18:24:42 ======================================================================\r\nJun 10 18:24:42 ERROR [100.075s]: test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn)\r\nJun 10 18:24:42 ----------------------------------------------------------------------\r\nJun 10 18:24:42 Traceback (most recent call last):\r\nJun 10 18:24:42   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 10 18:24:42     self._join_processes(fn)\r\nJun 10 18:24:42   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 10 18:24:42     self._check_return_codes(elapsed_time)\r\nJun 10 18:24:42   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 344, in _check_return_codes\r\nJun 10 18:24:42     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nJun 10 18:24:42 RuntimeError: Process 2 terminated or timed out after 100.05913996696472 seconds\r\nJun 10 18:24:42 \r\nJun 10 18:24:42 ----------------------------------------------------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/37409",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/37409",
      "id": 608167791,
      "node_id": "MDU6SXNzdWU2MDgxNjc3OTE=",
      "number": 37409,
      "title": "Compatibility of subset dataset with disabled batch sampling",
      "user": {
        "login": "dvirginz",
        "id": 31047807,
        "node_id": "MDQ6VXNlcjMxMDQ3ODA3",
        "avatar_url": "https://avatars2.githubusercontent.com/u/31047807?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dvirginz",
        "html_url": "https://github.com/dvirginz",
        "followers_url": "https://api.github.com/users/dvirginz/followers",
        "following_url": "https://api.github.com/users/dvirginz/following{/other_user}",
        "gists_url": "https://api.github.com/users/dvirginz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dvirginz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dvirginz/subscriptions",
        "organizations_url": "https://api.github.com/users/dvirginz/orgs",
        "repos_url": "https://api.github.com/users/dvirginz/repos",
        "events_url": "https://api.github.com/users/dvirginz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dvirginz/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1076923878,
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader",
          "name": "module: dataloader",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.utils.data.DataLoader and Sampler"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 4,
      "created_at": "2020-04-28T09:32:27Z",
      "updated_at": "2020-10-17T11:03:24Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "I think there is a compatibility issue with disabled batch sampling and subset dataset\r\nThe use-case - define custom batch sampling, and split the dataset using PyTorch split utility function\r\nHere's a minimal working example\r\n```\r\nself.train_dataset, self.val_dataset, self.test_dataset = torch.utils.data.random_split(\r\n            self.dataset, [100, 100, 100])\r\n\r\nloader = DataLoader(\r\n                dataset=self.train_dataset,\r\n                batch_size=None,\r\n                batch_sampler=None,\r\n                sampler=BatchSampler(\r\n                    SequentialSampler(dataset), batch_size=self.hparams.batch_size, drop_last=False),\r\n                num_workers=self.hparams.num_data_workers,\r\n            )\r\n```\r\nAnd when iterating the subset datasets this is the error\r\n```\r\nException has occurred: TypeError\r\nlist indices must be integers or slices, not list\r\n  File \"/path/utils/data/dataset.py\", line 257, in __getitem__\r\n    return self.dataset[self.indices[idx]]\r\n  File \"/path/utils/data/_utils/fetch.py\", line 46, in fetch\r\n    data = self.dataset[possibly_batched_index]\r\n  File \"/path/utils/data/dataloader.py\", line 385, in _next_data\r\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\r\n  File \"/path/utils/data/dataloader.py\", line 345, in __next__\r\n    data = self._next_data()\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py\", line 251, in _evaluate\r\n    for batch_idx, batch in enumerate(dataloader):\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py\", line 843, in run_pretrain_routine\r\n    False)\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py\", line 477, in single_gpu_train\r\n    self.run_pretrain_routine(model)\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py\", line 704, in fit\r\n    self.single_gpu_train(model)\r\n  File \"/path/train.py\", line 152, in main_train\r\n    trainer.fit(model)\r\n  File \"/path/train.py\", line 66, in main\r\n    main_train(model_class_pointer, hyperparams, logger)\r\n  File \"/path/train.py\", line 161, in <module>\r\n    main()\r\n  File \"/path/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/path/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/path/lib/python3.7/runpy.py\", line 263, in run_path\r\n    pkg_name=pkg_name, script_name=fname)\r\n  File \"/path/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/path/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n```\r\n\r\nAs the self.indices of the `subset` object is a simple python list.\r\n\r\nPlease refer to the forum post, where @ptrblck  approves reproducing the bug and offering a workaround.\n\ncc @SsnL",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/37495",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/37495",
      "id": 608912043,
      "node_id": "MDU6SXNzdWU2MDg5MTIwNDM=",
      "number": 37495,
      "title": "DISABLED test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)",
      "user": {
        "login": "mruberry",
        "id": 38511765,
        "node_id": "MDQ6VXNlcjM4NTExNzY1",
        "avatar_url": "https://avatars3.githubusercontent.com/u/38511765?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mruberry",
        "html_url": "https://github.com/mruberry",
        "followers_url": "https://api.github.com/users/mruberry/followers",
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}",
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions",
        "organizations_url": "https://api.github.com/users/mruberry/orgs",
        "repos_url": "https://api.github.com/users/mruberry/repos",
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mruberry/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20quantization",
          "name": "oncall: quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "raghuramank100",
        "id": 48835916,
        "node_id": "MDQ6VXNlcjQ4ODM1OTE2",
        "avatar_url": "https://avatars1.githubusercontent.com/u/48835916?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/raghuramank100",
        "html_url": "https://github.com/raghuramank100",
        "followers_url": "https://api.github.com/users/raghuramank100/followers",
        "following_url": "https://api.github.com/users/raghuramank100/following{/other_user}",
        "gists_url": "https://api.github.com/users/raghuramank100/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/raghuramank100/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/raghuramank100/subscriptions",
        "organizations_url": "https://api.github.com/users/raghuramank100/orgs",
        "repos_url": "https://api.github.com/users/raghuramank100/repos",
        "events_url": "https://api.github.com/users/raghuramank100/events{/privacy}",
        "received_events_url": "https://api.github.com/users/raghuramank100/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "raghuramank100",
          "id": 48835916,
          "node_id": "MDQ6VXNlcjQ4ODM1OTE2",
          "avatar_url": "https://avatars1.githubusercontent.com/u/48835916?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/raghuramank100",
          "html_url": "https://github.com/raghuramank100",
          "followers_url": "https://api.github.com/users/raghuramank100/followers",
          "following_url": "https://api.github.com/users/raghuramank100/following{/other_user}",
          "gists_url": "https://api.github.com/users/raghuramank100/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/raghuramank100/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/raghuramank100/subscriptions",
          "organizations_url": "https://api.github.com/users/raghuramank100/orgs",
          "repos_url": "https://api.github.com/users/raghuramank100/repos",
          "events_url": "https://api.github.com/users/raghuramank100/events{/privacy}",
          "received_events_url": "https://api.github.com/users/raghuramank100/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-04-29T09:33:17Z",
      "updated_at": "2020-08-03T21:58:47Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "This test is failing intermittently on multiple builds with increasing frequency recently and no clear cause. \r\n\r\n```\r\nApr 29 09:14:17 ======================================================================\r\nApr 29 09:14:17 ERROR [0.030s]: test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)\r\nApr 29 09:14:17 ----------------------------------------------------------------------\r\nApr 29 09:14:17 Traceback (most recent call last):\r\nApr 29 09:14:17   File \"/var/lib/jenkins/workspace/test/quantization/test_quantize.py\", line 862, in test_default_quantized_lstm\r\nApr 29 09:14:17     y, (h, c) = cell_dq(x, (h, c))\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 562, in __call__\r\nApr 29 09:14:17     result = self.forward(*input, **kwargs)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 351, in forward\r\nApr 29 09:14:17     return self.forward_tensor(input, hx)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 312, in forward_tensor\r\nApr 29 09:14:17     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 293, in forward_impl\r\nApr 29 09:14:17     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nApr 29 09:14:17 RuntimeError: In ChooseQuantizationParams, min should be less than or equal to max\r\n```\r\n\n\ncc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo @ezyang @gchanan @zou3519",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/32644",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/32644",
      "id": 555422490,
      "node_id": "MDU6SXNzdWU1NTU0MjI0OTA=",
      "number": 32644,
      "title": "DISABLED test_quantized_rnn (test_quanization.PostTrainingDynamicQuantTest)",
      "user": {
        "login": "rohan-varma",
        "id": 8039770,
        "node_id": "MDQ6VXNlcjgwMzk3NzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rohan-varma",
        "html_url": "https://github.com/rohan-varma",
        "followers_url": "https://api.github.com/users/rohan-varma/followers",
        "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
        "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
        "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
        "repos_url": "https://api.github.com/users/rohan-varma/repos",
        "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20quantization",
          "name": "oncall: quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "z-a-f",
        "id": 4216323,
        "node_id": "MDQ6VXNlcjQyMTYzMjM=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/z-a-f",
        "html_url": "https://github.com/z-a-f",
        "followers_url": "https://api.github.com/users/z-a-f/followers",
        "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
        "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
        "organizations_url": "https://api.github.com/users/z-a-f/orgs",
        "repos_url": "https://api.github.com/users/z-a-f/repos",
        "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
        "received_events_url": "https://api.github.com/users/z-a-f/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "z-a-f",
          "id": 4216323,
          "node_id": "MDQ6VXNlcjQyMTYzMjM=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/z-a-f",
          "html_url": "https://github.com/z-a-f",
          "followers_url": "https://api.github.com/users/z-a-f/followers",
          "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
          "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
          "organizations_url": "https://api.github.com/users/z-a-f/orgs",
          "repos_url": "https://api.github.com/users/z-a-f/repos",
          "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
          "received_events_url": "https://api.github.com/users/z-a-f/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 15,
      "created_at": "2020-01-27T08:22:49Z",
      "updated_at": "2020-03-06T03:05:33Z",
      "closed_at": null,
      "author_association": "MEMBER",
      "active_lock_reason": null,
      "body": "## üêõ Bug\r\n\r\ntes_quantized_rnn is flaky, see https://app.circleci.com/jobs/github/pytorch/pytorch/4343194\r\nSee example failure: \r\n```\r\nJan 26 08:10:23 ======================================================================\r\nJan 26 08:10:23 ERROR [0.186s]: test_quantized_rnn (__main__.PostTrainingDynamicQuantTest)\r\nJan 26 08:10:23 ----------------------------------------------------------------------\r\nJan 26 08:10:23 Traceback (most recent call last):\r\nJan 26 08:10:23   File \"test_quantization.py\", line 722, in test_quantized_rnn\r\nJan 26 08:10:23     y, (h, c) = cell_dq(x, (h, c))\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 540, in __call__\r\nJan 26 08:10:23     result = self.forward(*input, **kwargs)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 373, in forward\r\nJan 26 08:10:23     return self.forward_tensor(input, hx)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 334, in forward_tensor\r\nJan 26 08:10:23     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 315, in forward_impl\r\nJan 26 08:10:23     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nJan 26 08:10:23 RuntimeError: quantization scale should be > 0\r\n```\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34213",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34213",
      "id": 575502768,
      "node_id": "MDU6SXNzdWU1NzU1MDI3Njg=",
      "number": 34213,
      "title": "DISABLED test_script_pack_padded_sequence (test_jit.TestScript)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20jit",
          "name": "oncall: jit",
          "color": "c5def5",
          "default": false,
          "description": "Add this issue/PR to JIT oncall triage queue"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-04T15:29:15Z",
      "updated_at": "2020-03-09T17:09:59Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Previous failed runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682966\r\n\r\nSubsequent succeeded runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682247\r\nhttps://circleci.com/gh/pytorch/pytorch/4682241\r\n\r\nToday, it consistently fails:\r\nhttps://circleci.com/gh/pytorch/pytorch/4687625\r\nhttps://circleci.com/gh/pytorch/pytorch/4687610\r\nhttps://circleci.com/gh/pytorch/pytorch/4686149\r\n\r\n@ljk53 tried reverting the seemingly culprit PR #32814 and #34055, but the error persist. \r\n\r\nI am going to disable this test while JIT team investigating it. \n\ncc @ezyang @gchanan @zou3519 @suo",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40391",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40391/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40391/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40391/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40391",
      "id": 643299967,
      "node_id": "MDU6SXNzdWU2NDMyOTk5Njc=",
      "number": 40391,
      "title": "Mkldnn modules should throw RuntimeErrors if invoked when mkldnn is disabled",
      "user": {
        "login": "ngimel",
        "id": 15841449,
        "node_id": "MDQ6VXNlcjE1ODQxNDQ5",
        "avatar_url": "https://avatars3.githubusercontent.com/u/15841449?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ngimel",
        "html_url": "https://github.com/ngimel",
        "followers_url": "https://api.github.com/users/ngimel/followers",
        "following_url": "https://api.github.com/users/ngimel/following{/other_user}",
        "gists_url": "https://api.github.com/users/ngimel/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ngimel/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ngimel/subscriptions",
        "organizations_url": "https://api.github.com/users/ngimel/orgs",
        "repos_url": "https://api.github.com/users/ngimel/repos",
        "events_url": "https://api.github.com/users/ngimel/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ngimel/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1303456553,
          "node_id": "MDU6TGFiZWwxMzAzNDU2NTUz",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20mkldnn",
          "name": "module: mkldnn",
          "color": "f7e101",
          "default": false,
          "description": "Related to Intel IDEEP/MKL-DNN (mkldnn) integration"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "XiaobingSuper",
        "id": 16217777,
        "node_id": "MDQ6VXNlcjE2MjE3Nzc3",
        "avatar_url": "https://avatars1.githubusercontent.com/u/16217777?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/XiaobingSuper",
        "html_url": "https://github.com/XiaobingSuper",
        "followers_url": "https://api.github.com/users/XiaobingSuper/followers",
        "following_url": "https://api.github.com/users/XiaobingSuper/following{/other_user}",
        "gists_url": "https://api.github.com/users/XiaobingSuper/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/XiaobingSuper/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/XiaobingSuper/subscriptions",
        "organizations_url": "https://api.github.com/users/XiaobingSuper/orgs",
        "repos_url": "https://api.github.com/users/XiaobingSuper/repos",
        "events_url": "https://api.github.com/users/XiaobingSuper/events{/privacy}",
        "received_events_url": "https://api.github.com/users/XiaobingSuper/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "XiaobingSuper",
          "id": 16217777,
          "node_id": "MDQ6VXNlcjE2MjE3Nzc3",
          "avatar_url": "https://avatars1.githubusercontent.com/u/16217777?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/XiaobingSuper",
          "html_url": "https://github.com/XiaobingSuper",
          "followers_url": "https://api.github.com/users/XiaobingSuper/followers",
          "following_url": "https://api.github.com/users/XiaobingSuper/following{/other_user}",
          "gists_url": "https://api.github.com/users/XiaobingSuper/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/XiaobingSuper/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/XiaobingSuper/subscriptions",
          "organizations_url": "https://api.github.com/users/XiaobingSuper/orgs",
          "repos_url": "https://api.github.com/users/XiaobingSuper/repos",
          "events_url": "https://api.github.com/users/XiaobingSuper/events{/privacy}",
          "received_events_url": "https://api.github.com/users/XiaobingSuper/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-06-22T19:10:06Z",
      "updated_at": "2020-06-23T19:36:50Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Currently the following script will succeed:\r\n```\r\nimport torch\r\nimport copy\r\nfrom torch.utils import mkldnn as mkldnn_utils\r\ngroups=1\r\nN = 32\r\nC = 32\r\nM = 32\r\nx = torch.randn(N, C, 56, 56, dtype=torch.float).to_mkldnn()\r\nconv2d = torch.nn.Conv2d(in_channels=C,\r\n                            out_channels=M,\r\n                            kernel_size=3,\r\n                            padding=1)\r\nmkldnn_conv2d = mkldnn_utils.to_mkldnn(copy.deepcopy(conv2d))\r\nwith torch.backends.mkldnn.flags(enabled=False):\r\n    y_mkldnn = mkldnn_conv2d(x).to_dense()\r\n```\r\nIt is confusing that when mkldnn is disabled, one can still call mkldnn functions. An attempt to do so should throw a RuntimeError. \r\n\n\ncc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34432",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34432",
      "id": 577434425,
      "node_id": "MDU6SXNzdWU1Nzc0MzQ0MjU=",
      "number": 34432,
      "title": "DISABLED test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20flaky-tests",
          "name": "module: flaky-tests",
          "color": "f7e101",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/oncall:%20distributed",
          "name": "oncall: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Add this issue/PR to distributed oncall triage queue"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "pritamdamania87",
          "id": 9958665,
          "node_id": "MDQ6VXNlcjk5NTg2NjU=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/pritamdamania87",
          "html_url": "https://github.com/pritamdamania87",
          "followers_url": "https://api.github.com/users/pritamdamania87/followers",
          "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
          "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
          "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
          "repos_url": "https://api.github.com/users/pritamdamania87/repos",
          "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
          "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-08T02:42:25Z",
      "updated_at": "2020-05-06T21:19:46Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/20231//console\r\n\r\n```\r\n22:09:03 ======================================================================\r\n22:09:03 FAIL: test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)\r\n22:09:03 ----------------------------------------------------------------------\r\n22:09:03 Traceback (most recent call last):\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\n22:09:03     self._join_processes(fn)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in _join_processes\r\n22:09:03     self._check_return_codes(elapsed_time)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 276, in _check_return_codes\r\n22:09:03     self.assertEqual(p.exitcode, first_process.exitcode)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 915, in assertEqual\r\n22:09:03     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\r\n22:09:03 AssertionError: 16 not less than or equal to 1e-05 : \r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar",
      "performed_via_github_app": null,
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/31750",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/31750",
      "id": 544251558,
      "node_id": "MDU6SXNzdWU1NDQyNTE1NTg=",
      "number": 31750,
      "title": "DISABLED test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset10::test_interpolate_downsample",
      "user": {
        "login": "Krovatkin",
        "id": 5086322,
        "node_id": "MDQ6VXNlcjUwODYzMjI=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5086322?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Krovatkin",
        "html_url": "https://github.com/Krovatkin",
        "followers_url": "https://api.github.com/users/Krovatkin/followers",
        "following_url": "https://api.github.com/users/Krovatkin/following{/other_user}",
        "gists_url": "https://api.github.com/users/Krovatkin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Krovatkin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Krovatkin/subscriptions",
        "organizations_url": "https://api.github.com/users/Krovatkin/orgs",
        "repos_url": "https://api.github.com/users/Krovatkin/repos",
        "events_url": "https://api.github.com/users/Krovatkin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Krovatkin/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1679533716,
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped",
          "name": "skipped",
          "color": "bfdadc",
          "default": false,
          "description": "Denotes a (flaky) test currently skipped in CI."
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2019-12-31T19:03:16Z",
      "updated_at": "2020-01-02T14:49:19Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Temporarily disabling a flakey test.",
      "performed_via_github_app": null,
      "score": 0.0
    }
  ]
}
