{
  "total_count": 2,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/30848",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/30848/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/30848/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/30848/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/30848",
      "id": 533639085,
      "node_id": "MDU6SXNzdWU1MzM2MzkwODU=",
      "number": 30848,
      "title": "DISABLED test_max_pool2d (__main__.TestQuantizedOps)",
      "user": {
        "login": "eellison",
        "id": 11477974,
        "node_id": "MDQ6VXNlcjExNDc3OTc0",
        "avatar_url": "https://avatars2.githubusercontent.com/u/11477974?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eellison",
        "html_url": "https://github.com/eellison",
        "followers_url": "https://api.github.com/users/eellison/followers",
        "following_url": "https://api.github.com/users/eellison/following{/other_user}",
        "gists_url": "https://api.github.com/users/eellison/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eellison/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eellison/subscriptions",
        "organizations_url": "https://api.github.com/users/eellison/orgs",
        "repos_url": "https://api.github.com/users/eellison/repos",
        "events_url": "https://api.github.com/users/eellison/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eellison/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/quantization",
          "name": "quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2019-12-05T22:38:00Z",
      "updated_at": "2019-12-05T23:13:05Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "## üêõ Bug\r\n\r\n19:19:52 ERROR: test_max_pool2d (__main__.TestQuantizedOps)\r\n19:19:52 ----------------------------------------------------------------------\r\n19:19:52 Traceback (most recent call last):\r\n19:19:52   File \"test_quantized.py\", line 403, in test_max_pool2d\r\n19:19:52     min_side=1, max_side=10),\r\n19:19:52   File \"/usr/local/lib/python3.6/dist-packages/hypothesis/core.py\", line 991, in wrapped_test\r\n19:19:52     raise the_error_hypothesis_found\r\n19:19:52   File \"/usr/local/lib/python3.6/dist-packages/hypothesis/core.py\", line 950, in wrapped_test\r\n19:19:52     state.run()\r\n19:19:52   File \"/usr/local/lib/python3.6/dist-packages/hypothesis/core.py\", line 686, in run\r\n19:19:52     info.__expected_traceback,\r\n19:19:52   File \"/usr/local/lib/python3.6/dist-packages/hypothesis/core.py\", line 582, in execute\r\n19:19:52     % (test.__name__, text_repr[0])\r\n19:19:52   File \"/usr/local/lib/python3.6/dist-packages/hypothesis/core.py\", line 741, in __flaky\r\n19:19:52     raise Flaky(message)\r\n19:19:52 hypothesis.errors.Flaky: Hypothesis test_max_pool2d(self=<__main__.TestQuantizedOps testMethod=test_max_pool2d>, X=(array([[[[-75., -75., -75., ..., -75., -75., -75.],\r\n\r\n<!-- Add any other context about the problem here. -->\r\n\r\nFrom: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/10054//console\r\n\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/29959",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/29959/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/29959/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/29959/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/29959",
      "id": 523784646,
      "node_id": "MDU6SXNzdWU1MjM3ODQ2NDY=",
      "number": 29959,
      "title": "DISABLED test_async_grad_guard_with_grad (jit.test_async.TestAsync)",
      "user": {
        "login": "zdevito",
        "id": 370202,
        "node_id": "MDQ6VXNlcjM3MDIwMg==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/370202?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/zdevito",
        "html_url": "https://github.com/zdevito",
        "followers_url": "https://api.github.com/users/zdevito/followers",
        "following_url": "https://api.github.com/users/zdevito/following{/other_user}",
        "gists_url": "https://api.github.com/users/zdevito/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/zdevito/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zdevito/subscriptions",
        "organizations_url": "https://api.github.com/users/zdevito/orgs",
        "repos_url": "https://api.github.com/users/zdevito/repos",
        "events_url": "https://api.github.com/users/zdevito/events{/privacy}",
        "received_events_url": "https://api.github.com/users/zdevito/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2019-11-16T03:43:54Z",
      "updated_at": "2019-11-19T15:04:09Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Test issues please ignore.\r\nThis is not a real issue, but a test that the presence of this issue causes the code in the PR https://github.com/pytorch/pytorch/pull/29944 to skip the test named in this issue.\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @suo",
      "score": 0.0
    }
  ]
}
